### ISSUE TITLE
compare to VPD

### ISSUE THREAD

**Issue by yuzhang03** [Adonis-galaxy/WorDepth#3]
Hi Ziyao,

I noticed that [VPD](https://arxiv.org/pdf/2303.02153)[97] was mentioned in the Related Work twice. I was wondering why it wasn’t included in Table 1 as one of the baselines for comparison. Is the setup of WorDepth different from VPD, making a direct comparison unfair, or is there another reason I might have missed?

Thanks!

**Comment by Adonis-galaxy** [comment]
Hi, thank you very much for your question~ VPD was not included in the experiment comparison because it relies on a pre-trained diffusion model as its backbone. To ensure a fair comparison, we have listed the backbones used by each method in the experiment table and specifically highlighted those that utilize the same backbone (Swin-L) as our approach, to demonstrate the effectiveness of our approach.

**Comment by yuzhang03** [comment]
That makes sense, thank you!
