### ISSUE TITLE
About the "prior_mean" in the code

### ISSUE THREAD

**Issue by leilai125** [Adonis-galaxy/WorDepth#5]
Hi,

Thanks for your work. I wonder how the changing of prior_mean will affect the model performance. Is the model performance sensitive to this hyper-parameter? I think it is a pretty strong prior for the dataset. We may not be able to have this prior in most of the realistic scenarios.

Thanks!

**Comment by Adonis-galaxy** [comment]
Hi. We follow previous works to use this prior mean (VA-DepthNet, BTS). The prior mean is a statistical mean value of the depth for the training and evaluation dataset, serving as a bias that makes the depth prediction easier to learn. By modifying it simultaneously on both the training and evaluation sets, the model can also learn the bias by itself, assuming the training set and the evaluation set are from the same distribution. Since the model tries to minimize the prediction error in the training set, it will automatically learn such a bias term.
